<?php

namespace ContainerKbysT5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0ROpL1RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0ROpL1R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0ROpL1R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProduitsController::delete' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\ProduitsController::edit' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\ProduitsController::index' => ['privates', '.service_locator.xfMbnwT', 'get_ServiceLocator_XfMbnwTService', true],
            'App\\Controller\\ProduitsController::show' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ProduitsController:delete' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\ProduitsController:edit' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'App\\Controller\\ProduitsController:index' => ['privates', '.service_locator.xfMbnwT', 'get_ServiceLocator_XfMbnwTService', true],
            'App\\Controller\\ProduitsController:show' => ['privates', '.service_locator.ZE81RhG', 'get_ServiceLocator_ZE81RhGService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ProduitsController::delete' => '?',
            'App\\Controller\\ProduitsController::edit' => '?',
            'App\\Controller\\ProduitsController::index' => '?',
            'App\\Controller\\ProduitsController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProduitsController:delete' => '?',
            'App\\Controller\\ProduitsController:edit' => '?',
            'App\\Controller\\ProduitsController:index' => '?',
            'App\\Controller\\ProduitsController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
