<?php

namespace ContainerKbysT5x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailListTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MailListType' shared autowired service.
     *
     * @return \App\Form\MailListType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MailListType.php';

        return $container->privates['App\\Form\\MailListType'] = new \App\Form\MailListType();
    }
}
