<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKIG8xK3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKIG8xK3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKIG8xK3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKIG8xK3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKIG8xK3\App_KernelDevDebugContainer([
    'container.build_hash' => 'KIG8xK3',
    'container.build_id' => '2a3344da',
    'container.build_time' => 1630173772,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKIG8xK3');
