<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5clBlk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5clBlk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB5clBlk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB5clBlk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB5clBlk\App_KernelDevDebugContainer([
    'container.build_hash' => 'B5clBlk',
    'container.build_id' => 'cc591c5c',
    'container.build_time' => 1630084580,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5clBlk');
